---
# handlers file for rhel7_clustering
- shell: pcs cluster status
  when: inventory_hostname == groups.all[0]
  register: pcs_cluster_status
  tags: cluster_status
  listen: cluster_status

- debug: msg="{{ pcs_cluster_status.stdout_lines }}"
  when: inventory_hostname == groups.all[0]
  tags: cluster_status
  listen: cluster_status
